### ISSUE TITLE
Question: BR vs HF-Patch

### ISSUE THREAD

**Issue by jdoexbox360** [ManlyMarco/KKS-HF_Patch#1]
What are the differences between HF-patcha dn why do people install HF-patch over betterrepack? Is there any major differences (other than there being a preinstalled base game?) Thanks.

**Comment by ManlyMarco** [comment]
If you have bought the game and installed it then you'll want to use the patch. There are some differences but it doesn't matter as much, you can just get the one released the latest if you don't care about download sizes.
