### ISSUE TITLE
Release Numbering Incorrect

### ISSUE THREAD

**Issue by HUEMOB** [ManlyMarco/KKS-HF_Patch#3]
1.10 being the latest version doesnt make sense 1.10 is equivalent to 1.1. what should come after 1.9 would be 1.91 then 1.92 up to 1.99 and then 2.0. Maybe you could renumber all the other releases to by 1.00, 1.01, 1.02.... 1.09, 1.10 or make the current version 2.0 or 1.91 but that wouldnt fit the them if all the others are .1 apart

**Comment by ManlyMarco** [comment]
No, it's correct as it is. https://semver.org
