### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by phes3456** [ManlyMarco/KKS-HF_Patch#7]
![1721466552035](https://github.com/user-attachments/assets/8f8b30e6-4eb9-4991-ba28-8f557559d1d0)
Friends, I need help. After using Koikatsu Sunshine HF Patch v1.19, the game crashes inexplicably after a while after starting it. How should I solve this problem?

**Comment by phes3456** [comment]
Brother, I really need help. I hope you can give me some response.

**Comment by ManlyMarco** [comment]
Remove KKS_PostProcessingEffect.dll or wait for next HF Patch update.
