### ISSUE TITLE
Question: Release v1.20 Update?

### ISSUE THREAD

**Issue by Mirrorman95** [ManlyMarco/KKS-HF_Patch#8]
I have a question about the latest commit. It says: "Seiun-Sky Release v1.20 - commit 72e9b6e 8 hours ago".
But when I try to go to https://github.com/ManlyMarco/KKS-HF_Patch/releases/tag/v1.20 , it gives me a 404 error. I checked all of the commits Seiun-Sky did on GitHub repositories this month, and in all of them, the commit version number matches the latest release's version number. Except this one. And the public Patreon post for the HF Patch for KKS hasn't been updated, either. I'm not trying to complain, I just want to know: Is it a mistake? Or is it just taking a while for the update to be released?

**Comment by ManlyMarco** [comment]
The patch was still in staging.
